1 - 
SELECT ALUNO.Nome 
FROM ALUNO, TURMA, PROFESSOR
WHERE TURMA.PROFESSOR_id = PROFESSOR.id AND PROFESSOR.nome = 'JOAO PEDRO';

2 -
SELECT TURMA.dia_da_semana
FROM TURMA, DISCIPLINA
WHERE TURMA.DISCIPLINA_id = DISCIPLINA.id AND DISCIPLINA.nome = 'MATEMATICA' ;

3 - 
SELECT ALUNO.id, ALUNO.Nome
FROM ALUNO,  TURMA, DISCIPLINA
WHERE (ALUNO.id = TURMA.ALUNO_id AND TURMA.DISCIPLINA_id = DISCIPLINA.id 
AND DISCIPLINA.nome = 'MATEMATICA') AND (ALUNO.id = TURMA.ALUNO_id 
AND TURMA.DISCIPLINA_id = DISCIPLINA.id AND DISCIPLINA.nome = 'FISICA');

4 - 
SELECT DISCIPLINA.id, DISCIPLINA.nome
FROM DISCIPLINA
WHERE NOT EXISTS ( SELECT TURMA.id FROM TURMA 
WHERE TURMA.DISCIPLINA_id = DISCIPLINA.id);

5 - 
SELECT ALUNO.id, ALUNO.Nome
FROM ALUNO,  TURMA, DISCIPLINA
WHERE (ALUNO.id = TURMA.ALUNO_id AND TURMA.DISCIPLINA_id = DISCIPLINA.id 
AND DISCIPLINA.nome = 'MATEMATICA') 
AND NOT (ALUNO.id = TURMA.ALUNO_id AND TURMA.DISCIPLINA_id = DISCIPLINA.id 
AND DISCIPLINA.nome = 'QUIMICA')